version: 2
jobs:
  build:
    working_directory: ~/thrift-parser
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  npm_token:
    steps:
      - run:
        command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
  publish:
    steps:
      - run:
          name: publish-npm
          command: npm publish

  workflows:
    version: 2
    build_publish:
        jobs:
          - build
          - publish:
              requires:
                - build
                - npm_token
              filters:
                tag: /(v)?[0-9]+(\.[0-9]+)*/
