version: 2
jobs:
  build:
    working_directory: ~/thrift-parser
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  deployment:
    npm:
      tag: /v[0-9]+(\.[0-9]+)*/
          commands:
        - npm publish
