defaults: &defaults
  working_directory: ~/thrift-parser
  docker:
    - image: circleci/node:6.10.3

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ./

  npm_token:
    <<: *defaults
    steps:
      - run:
          name: npm-token
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
      - run:
          name: publish-npm
          command: npm publish

workflows:
  version: 2
  build_publish:
      jobs:
        - build
        - npm_token
        - publish:
            requires:
              - build
              - npm_token
            filters:
              tags:
                only: /(v)?[0-9]+(\.[0-9]+)*/
