version: 2
jobs:
  build:
    working_directory: ~/thrift-parser
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
